name: digimuh
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip
  - tqdm
  - pandas
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - pytest
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - -e .
